"""Fleet-term ablation on the size mixture: the deployed size-mixture policy
(m1-bcb-guide-mix) against the same arm trained and evaluated without B_veh
(m1-bcb-guide-mix-noveh), on the three production-batch cells. Same
statistics as scripts/x2_ablation_noveh_report.py (the 10-module ablation).

Pre-specified hypothesis (fixed before the runs, 2026-10-04). The fleet term
sets the root bound on every production-batch instance: in
results/bound_terms.json (supplement table of root terms) B_veh is the active
term at the root on 20/20 instances of each of 50x25 v2+t0.6, 50x25 v2+t1.0
and 80x25 v3+t1.0. Removing it removes the only active term from the reward,
the action prices and the credit on these instances, so the ablation's
makespan is expected to be LONGER than the mixture's in all three cells.

Test. Per cell, per-instance means over seeds 301-303 for each arm; paired
one-sided Wilcoxon signed-rank test, alternative = mixture shorter than the
ablation; Holm correction over the three pre-specified cells, alpha 0.05;
PASS only if all three Holm-adjusted p are below alpha. W/T/L counts the
instances where the mixture is shorter / tied (|diff| <= 1e-6) / longer.
The six 10- and 15-module cells the mixture was also evaluated on are
descriptive only (mean relative difference and W/T/L, no test).

Inputs (greedy rollouts, GPU for both arms):
  mixture   results/scaleup/policy/{MIX}-s{s}_{cell}.json
            test_results/PPVCT/{cell}/Result_greedy+{MIX}-s{s}_{cell}.npy
  ablation  results/ablation/noveh_mix/policy/{NOVEH}-s{s}_{cell}.json
            results/ablation/noveh_mix/test_results/{cell}/Result_greedy+{NOVEH}-s{s}_{cell}.npy
  (written by scripts/run_x2_ablation_noveh_mix_eval.sh)

Usage:
  python scripts/x2_ablation_noveh_mix_report.py           # print only
  python scripts/x2_ablation_noveh_mix_report.py --write   # also patch the
      macro block of macros.tex and the supplement table (tab:novehmix)
      between the marker comments
      '% BEGIN generated by scripts/x2_ablation_noveh_mix_report.py' and
      '% END generated by scripts/x2_ablation_noveh_mix_report.py'
      in both files (appended to macros.tex the first time; the markers
      must already exist in supplementary.tex). --write refuses to run
      unless every cell is complete and the pre-specified test passes.
"""
import json
import os
import re
import sys

import numpy as np
from scipy.stats import wilcoxon

MIX = 'mix10-15-20x25+ppvct-mixed+m1-bcb-guide-mix'
NOVEH = 'mix10-15-20x25+ppvct-mixed+m1-bcb-guide-mix-noveh'
SEEDS = (301, 302, 303)
PRIMARY = ['50x25+ppvct-mixed+v2+t0.6', '50x25+ppvct-mixed+v2+t1.0',
           '80x25+ppvct-mixed+v3+t1.0']
DESCRIPTIVE = ['v1+t0.6', 'v2+t0.6', 'v1+t1.0', 'v2+t1.0',
               '15x25+ppvct-mixed+v2+t0.6', '15x25+ppvct-mixed+v2+t1.0']
ABL = 'results/ablation/noveh_mix'
ALPHA = 0.05
TOL = 1e-6
WRITE = '--write' in sys.argv
MACROS = 'paper/main_manuscript_bundle/macros.tex'
SUPP = 'paper/main_manuscript_bundle/supplementary.tex'
TAG = 'generated by scripts/x2_ablation_noveh_mix_report.py'
# cell -> (modules, |V|, tau/p) for the supplement table
GRID_SIZE = {'v1+t0.6': ('10', '1', '0.6'), 'v2+t0.6': ('10', '2', '0.6'),
             'v1+t1.0': ('10', '1', '1.0'), 'v2+t1.0': ('10', '2', '1.0'),
             '15x25+ppvct-mixed+v2+t0.6': ('15', '2', '0.6'),
             '15x25+ppvct-mixed+v2+t1.0': ('15', '2', '1.0')}
PROD_SIZE = {'50x25+ppvct-mixed+v2+t0.6': ('50', '2', '0.6'),
             '50x25+ppvct-mixed+v2+t1.0': ('50', '2', '1.0'),
             '80x25+ppvct-mixed+v3+t1.0': ('80', '3', '1.0')}
TABLE_ORDER = ['v1+t0.6', 'v1+t1.0', 'v2+t0.6', 'v2+t1.0',
               '15x25+ppvct-mixed+v2+t0.6', '15x25+ppvct-mixed+v2+t1.0']


def policy_rows(path):
    d = json.load(open(path))
    return d['rows'], d.get('device'), d.get('params')


def prod_arm(arm, cell, root):
    """{seed: (instance names, makespans)} for one arm on a production cell."""
    out, meta = {}, set()
    for s in SEEDS:
        p = f'{root}/{arm}-s{s}_{cell}.json'
        if not os.path.exists(p):
            continue
        rows, dev, par = policy_rows(p)
        names = sorted(rows)
        out[s] = (names, np.array([rows[n]['ms'] for n in names]))
        meta.add((dev, par))
    return out, meta


def grid_arm(arm, cell, root):
    out = {}
    for s in SEEDS:
        p = f'{root}/{cell}/Result_greedy+{arm}-s{s}_{cell}.npy'
        if os.path.exists(p):
            out[s] = np.load(p)[:, 0]
    return out


def compare(f, n):
    """f, n: per-instance 3-seed means (mixture, ablation)."""
    rel = 100.0 * (n.mean() - f.mean()) / f.mean()   # + means removing B_veh hurts
    d = f - n
    w, l = int((d < -TOL).sum()), int((d > TOL).sum())
    p = wilcoxon(f, n, alternative='less').pvalue if np.any(np.abs(d) > TOL) else 1.0
    return rel, f'{w}/{len(d) - w - l}/{l}', p


def holm(pvals):
    order = sorted(pvals, key=lambda c: pvals[c])
    k_tot, out, running = len(order), {}, 0.0
    for k, c in enumerate(order):
        running = max(running, min(1.0, (k_tot - k) * pvals[c]))
        out[c] = running
    return out


def main():
    rows, pvals = [], {}
    for cell in PRIMARY:
        f, mf = prod_arm(MIX, cell, 'results/scaleup/policy')
        n, mn = prod_arm(NOVEH, cell, f'{ABL}/policy')
        if sorted(f) != list(SEEDS) or sorted(n) != list(SEEDS):
            print(f'{cell}: incomplete (mixture seeds {sorted(f)}, ablation seeds {sorted(n)})')
            continue
        names = f[SEEDS[0]][0]
        assert all(f[s][0] == names and n[s][0] == names for s in SEEDS), \
            f'{cell}: instance sets differ between arms or seeds'
        if mf != mn or len(mf) != 1:
            print(f'  WARNING {cell}: (device, params) mixture {mf} vs ablation {mn}')
        fm = np.mean([f[s][1] for s in SEEDS], 0)
        nm = np.mean([n[s][1] for s in SEEDS], 0)
        rel, wtl, p = compare(fm, nm)
        pvals[cell] = p
        seedrel = [100.0 * (n[s][1].mean() - f[s][1].mean()) / f[s][1].mean() for s in SEEDS]
        rows.append((cell, fm.mean(), nm.mean(), rel, wtl, p, seedrel, len(fm)))

    hdr = (f'{"cell":27s} {"n":>3s} {"mixture":>9s} {"no B_veh":>9s} {"rel%":>7s} '
           f'{"W/T/L":>8s} {"p(1-sided)":>11s}  per-seed rel%')
    print(hdr)
    for cell, a, b, rel, wtl, p, sr, k in rows:
        print(f'{cell:27s} {k:3d} {a:9.1f} {b:9.1f} {rel:+7.2f} {wtl:>8s} {p:11.2e}  '
              + ' '.join(f'{x:+.2f}' for x in sr) + '  PRIMARY')

    if len(pvals) == len(PRIMARY):
        h = holm(pvals)
        verdict = all(h[c] < ALPHA for c in PRIMARY)
        print(f'\nPRE-SPECIFIED TEST (Holm over the {len(PRIMARY)} production cells, '
              f'alpha {ALPHA}): '
              + ', '.join(f'{c.split("+ppvct-mixed+")[0]} {c.split("+ppvct-mixed+")[1]} '
                          f'p_holm={h[c]:.2e}' for c in PRIMARY)
              + f' -> {"PASS" if verdict else "FAIL"}')
    else:
        print('\nPRE-SPECIFIED TEST not run: production cells incomplete')

    print('\nDescriptive (10- and 15-module cells, no test):')
    desc = {}
    for cell in DESCRIPTIVE:
        f = grid_arm(MIX, cell, 'test_results/PPVCT')
        n = grid_arm(NOVEH, cell, f'{ABL}/test_results')
        if sorted(f) != list(SEEDS) or sorted(n) != list(SEEDS):
            print(f'  {cell}: incomplete (mixture seeds {sorted(f)}, ablation seeds {sorted(n)})')
            continue
        fm = np.mean([f[s] for s in SEEDS], 0)
        nm = np.mean([n[s] for s in SEEDS], 0)
        assert fm.shape == nm.shape
        rel, wtl, _ = compare(fm, nm)
        seedrel = [100.0 * (n[s].mean() - f[s].mean()) / f[s].mean() for s in SEEDS]
        desc[cell] = (rel, wtl, seedrel, len(fm))
        print(f'  {cell:27s} n={len(fm):3d} mixture {fm.mean():8.1f} no B_veh {nm.mean():8.1f} '
              f'rel {rel:+6.2f}%  W/T/L {wtl}  per-seed '
              + ' '.join(f'{x:+.2f}' for x in seedrel))

    if rows:
        print('\n% ---- supplement table rows: cell & rel% & W/T/L & p_holm & per-seed rel% ----')
        h = holm(pvals) if len(pvals) == len(PRIMARY) else {}
        fmt = lambda x: f'{x:+.1f}'.replace('-0.0', '0.0').replace('+0.0', '0.0')
        for cell, a, b, rel, wtl, p, sr, k in rows:
            size, rest = cell.split('+ppvct-mixed+')
            ph = f'{h[cell]:.1e}' if cell in h else '--'
            print(f'{size} {rest} & ${fmt(rel)}$ & {wtl} & {ph} & '
                  + ', '.join(f'${fmt(x)}$' for x in sr) + ' \\\\')

    if WRITE:
        write(rows, pvals, desc)


def fmt1(x):
    return f'{x:+.1f}'.replace('-0.0', '0.0').replace('+0.0', '0.0')


def tex_p(p):
    m, e = f'{p:.1e}'.split('e')
    return f'{m}\\times10^{{{int(e)}}}'


def replace_block(path, body, append):
    """Replace the text between the BEGIN/END marker comments of this script."""
    s = open(path).read()
    pat = re.compile(r'(% BEGIN ' + re.escape(TAG) + r'\n).*?(% END '
                     + re.escape(TAG) + r')', re.S)
    if pat.search(s):
        s = pat.sub(lambda m: m.group(1) + body + m.group(2), s, count=1)
    elif append:
        s = s.rstrip('\n') + f'\n\n% BEGIN {TAG}\n{body}% END {TAG}\n'
    else:
        sys.exit(f'refusing --write: no marker comments in {path}')
    open(path, 'w').write(s)
    print(f'patched {path}')


def write(rows, pvals, desc):
    if len(rows) != len(PRIMARY) or len(desc) != len(DESCRIPTIVE):
        sys.exit('refusing --write: cells incomplete')
    h = holm(pvals)
    if not all(h[c] < ALPHA for c in PRIMARY):
        sys.exit('refusing --write: the pre-specified test did not pass')
    by = {r[0]: r for r in rows}
    wtls = {by[c][4] for c in PRIMARY}
    assert len(wtls) == 1, f'W/T/L differ across the production cells: {wtls}'
    ph = max(h.values())
    seeds = [x for c in PRIMARY for x in by[c][6]]
    small = [desc[c][0] for c in DESCRIPTIVE]
    m = [('AblVehMixDFiftyTSix', f'{by[PRIMARY[0]][3]:.1f}',
          '(no-veh - mixture)/mixture in %, 50x25 v2+t0.6, n=20, 3-seed means'),
         ('AblVehMixDFiftyTTen', f'{by[PRIMARY[1]][3]:.1f}', 'same, 50x25 v2+t1.0'),
         ('AblVehMixDEighty', f'{by[PRIMARY[2]][3]:.1f}', 'same, 80x25 v3+t1.0'),
         ('AblVehMixWtl', wtls.pop(), 'W/T/L (mixture shorter/tied/longer), identical in the three production cells'),
         ('AblVehMixPHolm', tex_p(ph),
          'largest Holm-adjusted one-sided Wilcoxon p over the three production cells ('
          + ', '.join(f'{h[c]:.2e}' for c in PRIMARY) + ')'),
         ('AblVehMixSeedMin', f'{min(seeds):.1f}', 'smallest per-seed relative difference in %, production cells'),
         ('AblVehMixSeedMax', f'{max(seeds):.1f}', 'largest per-seed relative difference in %, production cells'),
         ('AblVehMixSmallMin', f'{min(small):.1f}', 'smallest relative difference in %, six 10- and 15-module cells (descriptive, n=100)'),
         ('AblVehMixSmallMax', f'{max(small):.1f}', 'largest relative difference in %, same six cells')]
    body = ('% Fleet-term ablation on the size mixture: m1-bcb-guide-mix-noveh vs\n'
            '% m1-bcb-guide-mix, seeds 301-303, per-instance 3-seed means; test fixed\n'
            '% before the runs (see this script\'s docstring). Inputs: results/scaleup/policy,\n'
            '% results/ablation/noveh_mix, test_results/PPVCT.\n'
            + ''.join(f'\\newcommand{{\\{k}}}{{{v}}}  % {c}\n' for k, v, c in m))
    replace_block(MACROS, body, append=True)

    lines = [
        '\\begin{table}[htbp]', '\\centering',
        '\\caption{Makespan increase when the size-mixture policy is retrained '
        'without $\\Bveh$, relative to the deployed size-mixture policy. W/T/L '
        'counts the instances on which the deployed policy is shorter, equal, '
        'or longer.}',
        '\\label{tab:novehmix}', '\\begin{threeparttable}', '\\footnotesize',
        '\\setlength{\\tabcolsep}{3pt}',
        '\\begin{tabular}{@{}cccrrcc@{}}', '\\toprule',
        'Modules & $|V|$ & $\\bar\\tau/\\bar p$ & $n$ & Increase (\\%) & W/T/L & '
        'Per seed 301, 302, 303 (\\%) \\\\', '\\midrule']
    for c in PRIMARY:
        _, _, _, rel, wtl, _, sr, k = by[c]
        mo, v, t = PROD_SIZE[c]
        lines.append(f'${mo}$\\tnote{{a}} & ${v}$ & ${t}$ & {k} & ${fmt1(rel)}$ & {wtl} & '
                     + ', '.join(f'${fmt1(x)}$' for x in sr) + ' \\\\')
    lines.append('\\midrule')
    for c in TABLE_ORDER:
        rel, wtl, sr, k = desc[c]
        mo, v, t = GRID_SIZE[c]
        lines.append(f'${mo}$ & ${v}$ & ${t}$ & {k} & ${fmt1(rel)}$ & {wtl} & '
                     + ', '.join(f'${fmt1(x)}$' for x in sr) + ' \\\\')
    lines += [
        '\\bottomrule', '\\end{tabular}', '\\begin{tablenotes}\\footnotesize',
        '\\item Machines: 25. The 10- and 15-module rows are training sizes '
        'of the mixture and are descriptive.',
        f'\\item[a] Pre-specified test cells, each with Holm-adjusted '
        f'$p={tex_p(ph)}$.',
        '\\end{tablenotes}', '\\end{threeparttable}', '\\end{table}']
    replace_block(SUPP, '\n'.join(lines) + '\n', append=False)


if __name__ == '__main__':
    main()
