"""Breakdown recovery with the budgeted search arms: supplement table and macros.

Reads the ledgers written by scripts/x2_disruption.py
(results/disruption/{cell}.jsonl) and produces, for the two production cells
and both generators of the disrupted plan, the recovered makespan and the
wall time of every arm: right shift, best-of-nine rule re-dispatch, the
policy's re-plan, warm-started residual CP-SAT at 1, 10 and 60 s, and the
PDR-seeded GA at 10 and 60 s.

Conventions (those of scripts/x2_disruption_phase1.py and
scripts/x2_production_macros.py):
  * a value per instance; for an arm that depends on a training seed (the
    policy, and every arm when the disrupted plan is the policy's own) it is
    the mean over seeds 301/302/303;
  * makespan in hours as mean +- sample standard deviation (ddof=1) over the
    20 instances; wall is the mean over all records of that arm (seconds);
  * relative differences are the policy against the rival,
    100 * (mean(policy) - mean(rival)) / mean(rival), so the rival is the
    denominator, exactly as in Table S-XIII;
  * win/tie/loss of the policy, ties at 1e-6; paired two-sided Wilcoxon.

The macros are patched into macros.tex in place (or appended as one block the
first time); the table environment is printed, and with --write it replaces
the block between the two marker comments in supplementary.tex.

Usage:
  python scripts/x2_disruption_search_table.py           # print only
  python scripts/x2_disruption_search_table.py --write   # patch both files
"""
import glob
import json
import re
import sys
from collections import defaultdict

import numpy as np
from scipy.stats import wilcoxon

WRITE = '--write' in sys.argv
MACROS = 'paper/main_manuscript_bundle/macros.tex'
SUPP = 'paper/main_manuscript_bundle/supplementary.tex'
BEGIN = '% BEGIN generated by scripts/x2_disruption_search_table.py'
END = '% END generated by scripts/x2_disruption_search_table.py'
TOL = 1e-6
CELLS = (('50x25+ppvct-mixed+v2+t1.0', 'Fifty', '$50$, $2$, $1.0$'),
         ('80x25+ppvct-mixed+v3+t1.0', 'Eighty', '$80$, $3$, $1.0$'))
BASES = (('pdr', 'Dispatching plan'), ('policy', "Policy's plan"))
ROWS = (('right_shift', None, 'Right shift', '--'),
        ('pdr', None, 'Rule re-dispatch', '--'),
        ('policy', None, 'Policy re-plan', '--'),
        ('cpsat', 1.0, 'CP-SAT', '1'),
        ('cpsat', 10.0, 'CP-SAT', '10'),
        ('cpsat', 60.0, 'CP-SAT', '60'),
        ('ga', 10.0, 'GA', '10'),
        ('ga', 60.0, 'GA', '60'))
SEARCH = [r for r in ROWS if r[1] is not None]
FAST_CORES = '6-7'   # the two performance cores some GA runs used


def load():
    """recs[(cell, base, method, budget)] = list of records."""
    recs = defaultdict(list)
    for p in sorted(glob.glob('results/disruption/*.jsonl')):
        for line in open(p):
            if not line.strip():
                continue
            r = json.loads(line)
            assert r['validated'], f'unvalidated record in {p}: {r["key"]}'
            recs[(r['cell'], r['baseline_method'], r['method'],
                  r['budget_s'])].append(r)
    return recs


def per_instance(rs):
    acc = defaultdict(list)
    for r in rs:
        acc[r['instance']].append(r['makespan'])
    return {i: float(np.mean(v)) for i, v in acc.items()}


def rel(ours, rival):
    return 100.0 * (np.mean(ours) - np.mean(rival)) / np.mean(rival)


def wtl(ours, rival):
    d = np.asarray(ours) - np.asarray(rival)
    w, l = int((d < -TOL).sum()), int((d > TOL).sum())
    return f'{w}/{len(d) - w - l}/{l}'


def main():
    recs = load()

    table = {}                    # (cell, base, row index) -> (ms str, wall)
    cp_vs, ga_vs, ga_wall, pol_wall = [], [], [], {}
    cp_imp, wtl_cp, wtl_ga, pvals = [], set(), set(), []
    cp_wall_short = []            # CP-SAT mean wall at the 1-s and 10-s budgets
    over = defaultdict(list)
    fast, fast_total = 0, 0
    for cell, word, _ in CELLS:
        walls_pol = []
        for base, _ in BASES:
            vals, walls = {}, {}
            for k, (m, b, _, _) in enumerate(ROWS):
                rs = recs[(cell, base, m, b)]
                assert rs, f'no records for {cell} {base} {m} {b}'
                vals[k] = per_instance(rs)
                walls[k] = float(np.mean([r['wall_s'] for r in rs]))
            names = sorted(vals[2])
            assert len(names) == 20, (cell, base, len(names))
            for k in vals:
                assert sorted(vals[k]) == names, (cell, base, ROWS[k])
            arr = {k: np.array([vals[k][n] for n in names]) for k in vals}
            for k in arr:
                table[(cell, base, k)] = (arr[k].mean(), arr[k].std(ddof=1),
                                          walls[k])
            pol = arr[2]
            walls_pol.append(walls[2])
            rs_ms = arr[0]
            for k, (m, b, _, _) in enumerate(ROWS):
                if b is None:
                    continue
                g, s = rel(pol, arr[k]), wtl(pol, arr[k])
                p = float(wilcoxon(pol, arr[k]).pvalue)
                pvals.append(p)
                print(f'{cell[:2]} {base:6s} {m:5s} {b:4.0f}s  policy vs arm '
                      f'{g:+6.2f}%  W/T/L {s}  p={p:.1e}  wall {walls[k]:.1f}')
                if m == 'cpsat':
                    cp_vs.append(-g)
                    wtl_cp.add(s)
                    cp_imp.append(100.0 * (rs_ms.mean() - arr[k].mean())
                                  / rs_ms.mean())
                    if b in (1.0, 10.0):
                        cp_wall_short.append(walls[k])
                        assert np.allclose(arr[k], rs_ms, atol=TOL), \
                            f'CP-SAT changed the right shift at {b} s'
                else:
                    ga_vs.append(g)
                    wtl_ga.add(s)
                    ga_wall.append(walls[k])
                    rs_ = recs[(cell, base, m, b)]
                    over[word].append(float(np.mean(
                        [r['wall_s'] - b for r in rs_])))
                    if word == 'Eighty' and base == 'policy':
                        fast += sum(r['cores'] == FAST_CORES for r in rs_)
                        fast_total += len(rs_)
        pol_wall[word] = float(np.mean(walls_pol))
        # sanity: GA runs on the fast cores occur only where the note says
        for base, _ in BASES:
            for b in (10.0, 60.0):
                if (word, base) != ('Eighty', 'policy'):
                    assert all(r['cores'] != FAST_CORES for r in
                               recs[(cell, base, 'ga', b)])

    cp_zero = [c for c in cp_imp if c > TOL]
    macro('DisrCpVsPolMin', f'{min(cp_vs):.1f}',
          '(CP-SAT - policy)/CP-SAT in %, min over cells, plans, budgets 1/10/60 s')
    macro('DisrCpVsPolMax', f'{max(cp_vs):.1f}', 'same, max')
    macro('DisrCpImpMax', f'{max(cp_imp):.1f}',
          '(right shift - CP-SAT 60 s)/right shift in %, max; '
          f'0 at 1 and 10 s and at 80 modules ({len(cp_zero)} of '
          f'{len(cp_imp)} settings improve)')
    macro('DisrCpWtl', '/'.join(sorted(wtl_cp)) if len(wtl_cp) == 1 else '?',
          'policy vs CP-SAT, every cell, plan and budget')
    macro('DisrCpWallShortMin', f'{min(cp_wall_short):.0f}',
          'CP-SAT mean wall s per cell and plan at the 1-s and 10-s budgets, min')
    macro('DisrCpWallShortMax', f'{max(cp_wall_short):.0f}', 'same, max')
    macro('DisrGaVsPolMin', f'{min(ga_vs):.1f}',
          '(policy - GA)/GA in %, min over cells, plans, budgets 10/60 s')
    macro('DisrGaVsPolMax', f'{max(ga_vs):.1f}', 'same, max')
    macro('DisrGaWtl', '/'.join(sorted(wtl_ga)) if len(wtl_ga) == 1 else '?',
          'policy vs GA, every cell, plan and budget')
    macro('DisrGaWallMin', f'{min(ga_wall):.0f}',
          'GA mean wall s per cell, plan and budget, min')
    macro('DisrGaWallMax', f'{max(ga_wall):.0f}', 'same, max')
    for word in ('Fifty', 'Eighty'):
        macro(f'DisrPolWall{word}', f'{pol_wall[word]:.0f}',
              'policy re-plan mean wall s, both plans, one torch thread')
        macro(f'DisrGaOver{word}Low', f'{min(over[word]):.0f}',
              'GA mean (wall - budget) s, min over plans and budgets')
        macro(f'DisrGaOver{word}High', f'{max(over[word]):.0f}', 'same, max')
    macro('DisrGaFastRuns', f'{fast}',
          f'80-module GA runs on the policy plan that used cores {FAST_CORES}')
    macro('DisrGaFastTotal', f'{fast_total}', 'all such runs (3 seeds x 20 x 2 budgets)')
    pmax = max(pvals)
    m_, e_ = f'{pmax:.1e}'.split('e')
    macro('DisrSearchPmax', f'{m_}\\times10^{{{int(e_)}}}',
          'largest paired Wilcoxon p, policy vs every search arm')

    tex = render(table, fast)
    print('\n' + tex)
    print('% ---- macros')
    for name, value, note in OUT:
        print(f'\\newcommand{{\\{name}}}{{{value}}}  % {note}')
    if WRITE:
        patch_macros()
        s = open(SUPP).read()
        i, j = s.index(BEGIN), s.index(END)
        s = s[:i] + BEGIN + '\n' + tex + s[j:]
        open(SUPP, 'w').write(s)
        print(f'patched {SUPP}')


OUT = []


def macro(name, value, note):
    OUT.append((name, value, note))


def patch_macros():
    s = open(MACROS).read()
    block = []
    for name, value, note in OUT:
        new = f'\\newcommand{{\\{name}}}{{{value}}}  % {note}'
        pat = re.compile(r'^\\newcommand\{\\' + name + r'\}\{[^\n]*$', re.M)
        if pat.search(s):
            s = pat.sub(lambda m: new, s, count=1)
        else:
            block.append(new)
    if block:
        s = s.rstrip('\n') + '\n\n' + '\n'.join([
            '% ---- Recovery from a machine breakdown, budgeted search arms',
            '% (scripts/x2_disruption_search_table.py -> results/disruption/*.jsonl;',
            '% warm-started residual CP-SAT, 4 workers, and the PDR-seeded GA, wall-clock',
            '% budgets; same breakdowns, plans, seeds and instances as the no-search arms',
            '% above. Relative differences use the rival as denominator.)'] + block) + '\n'
    open(MACROS, 'w').write(s)
    print(f'patched {MACROS}: {len(OUT) - len(block)} rewritten, {len(block)} appended')


def render(table, fast=0):
    best = {}
    for cell, _, _ in CELLS:
        for base, _ in BASES:
            best[(cell, base)] = min(range(len(ROWS)),
                                     key=lambda k: table[(cell, base, k)][0])
    lines = [
        '\\begin{table*}[!t]',
        '\\centering',
        '\\caption{Recovery from a machine breakdown with the search arms added, '
        'by re-planning budget. Bold: shortest makespan in each column.}',
        '\\label{tab:disruptsearch}',
        '\\begin{threeparttable}',
        '\\footnotesize',
        '\\setlength{\\tabcolsep}{4pt}',
        '\\begin{tabular}{@{}lr' + 'rr' * 4 + '@{}}',
        '\\toprule',
        ' & & ' + ' & '.join(f'\\multicolumn{{4}}{{c}}{{Cell {lab}}}'
                             for _, _, lab in CELLS) + ' \\\\',
        '\\cmidrule(lr){3-6}\\cmidrule(l){7-10}',
        ' & & ' + ' & '.join(f'\\multicolumn{{2}}{{c}}{{{bl}}}'
                             for _ in CELLS for _, bl in BASES) + ' \\\\',
        '\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}'
        '\\cmidrule(l){9-10}',
        'Arm & Budget (s) & ' + ' & '.join(['Makespan & Wall (s)'] * 4)
        + ' \\\\',
        '\\midrule']
    for k, (_, _, name, bud) in enumerate(ROWS):
        cells = []
        for cell, _, _ in CELLS:
            for base, _ in BASES:
                mu, sd, w = table[(cell, base, k)]
                ms = f'{mu:.1f}$\\pm${sd:.1f}'
                if best[(cell, base)] == k:
                    ms = f'\\textbf{{{ms}}}'
                ws = '$<$0.1' if w < 0.05 else f'{w:.1f}'
                cells += [ms, ws]
        lines.append(f'{name} & {bud} & ' + ' & '.join(cells) + ' \\\\')
        if k == 2:
            lines.append('\\addlinespace')
    lines += [
        '\\bottomrule',
        '\\end{tabular}',
        '\\begin{tablenotes}\\footnotesize',
        '\\item Cell: modules, $|V|$, $\\bar\\tau/\\bar p$ (machines: 25). '
        'Makespan in hours, mean $\\pm$ standard deviation over the 20 '
        'instances. A per-instance value is the mean over three seeds for the '
        "policy and for every arm on the policy's plan. "
        'Wall: mean wall time per instance. CP-SAT is '
        'warm-started from the right-shifted plan and uses four workers. '
        'Both search arms exceed their budgets because work precedes the '
        'search clock. CP-SAT builds the residual model first, and the GA '
        'builds the nine rule-seeded chromosomes and evaluates its first '
        'population of 100, then finishes the generation in progress when '
        'the budget expires. The GA therefore exceeds its budget by '
        '\\DisrGaOverFiftyLow--\\DisrGaOverFiftyHigh~s at 50 modules and by '
        '\\DisrGaOverEightyLow--\\DisrGaOverEightyHigh~s at 80 modules. '
        + ("At 80 modules on the policy's plan, \\DisrGaFastRuns{} of the "
           '\\DisrGaFastTotal{} GA runs used two faster processor cores, which '
           'shortens their wall time. ' if fast else '') +
        'The rule and policy walls were measured '
        'while other jobs ran on the machine, so they are upper bounds. The policy outperforms CP-SAT at every '
        'budget in every column (win/tie/loss \\DisrCpWtl), and the GA '
        'outperforms the policy at every budget in every column '
        '(\\DisrGaWtl); all these comparisons have '
        '$p\\le\\DisrSearchPmax$.',
        '\\end{tablenotes}',
        '\\end{threeparttable}',
        '\\end{table*}']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    main()
