"""Deployment-cost macros and supplement table from the batch-1 latency probe.

Reads the two JSON files written by scripts/x2_latency_memory.py
(results/latency/x2_latency_memory_cpu.json and ..._cuda.json: the deployed
size-mixture policy, seeds 301-303, batch 1, one pinned core, one torch
thread, 3 instances per size at 10, 20, 50 and 80 modules) and derives:

  * macros (block between the two marker comments in macros.tex):
      LatEvtCpu{Ten,Twenty,Fifty,Eighty}  per-event ms incl. env step, CPU
      LatEvtGpu{Ten,Eighty}               same on the GPU
      LatFwdCpu{Ten,Eighty}               forward + greedy selection only, CPU
      LatFwdGpu{Min,Max}                  same on the GPU, min/max over sizes
      LatSchedCpu{Ten,Eighty}, LatSchedGpuEighty   end-to-end s per instance
      PeakRssCpu{Min,Max}, PeakRssGpu{Min,Max}  ru_maxrss of the cell process, MiB
      RssImport                           RSS after `import torch`, MiB (min)
      CudaAllocMax                        torch peak allocated device memory, MiB
      CkptBytes, CkptKiB                  checkpoint file size
  * the body rows of Table "Deployment cost by instance size" (block between
    the two marker comments in supplementary.tex).

Conventions (those of the probe's JSON "conventions" field):
  fwd    = policy forward + greedy action selection (+ cuda synchronize);
  event  = fwd + action copy to host + env.step (next state ready);
  end-to-end = instance read + env and bound construction + rollout;
  per-cell statistics pool every event of the 9 rollouts (3 instances x 3
  seeds); memory in MiB = KiB / 1024 (ru_maxrss is in KiB on Linux).

The parameter count is not a new macro: the script asserts that the
checkpoint's count equals \\ParamsTrain in macros.tex and the text reuses it.

Usage:
  python scripts/x2_latency_macros.py           # print only
  python scripts/x2_latency_macros.py --write   # patch macros.tex and supplementary.tex
"""
import json
import re
import sys

WRITE = '--write' in sys.argv
CPU = 'results/latency/x2_latency_memory_cpu.json'
GPU = 'results/latency/x2_latency_memory_cuda.json'
MACROS = 'paper/main_manuscript_bundle/macros.tex'
SUPP = 'paper/main_manuscript_bundle/supplementary.tex'
BEGIN = '% BEGIN generated by scripts/x2_latency_macros.py'
END = '% END generated by scripts/x2_latency_macros.py'
SIZES = (('10', 'Ten'), ('20', 'Twenty'), ('50', 'Fifty'), ('80', 'Eighty'))


def load(path, device):
    d = json.load(open(path))
    assert d['device'] == device and d['batch'] == 1, path
    assert d['torch_threads'] == 1 and d['omp_mkl_threads'] == 1, path
    assert d['cores_pinned'] and len(d['cores']) == 1, path
    assert d['seeds'] == [301, 302, 303], path
    assert set(d['cells']) == {s for s, _ in SIZES}, path
    for c in d['cells'].values():
        assert c['n_rollouts'] == 9, (path, c['cell'])
    return d


def ckpt(d):
    vals = {(r['checkpoint_bytes'], r['params'])
            for c in d['cells'].values() for r in c['seeds'].values()}
    assert len(vals) == 1, vals
    return vals.pop()


def cell_tex(cell):
    # '80x25+ppvct-mixed+v3+t1.0' -> '$80$, $3$, $1.0$'
    m = re.match(r'(\d+)x25\+ppvct-mixed\+v(\d+)\+t([\d.]+)$', cell)
    return f'${m.group(1)}$, ${m.group(2)}$, ${m.group(3)}$'


def main():
    cpu, gpu = load(CPU, 'cpu'), load(GPU, 'cuda')
    nbytes, params = ckpt(cpu)
    assert (nbytes, params) == ckpt(gpu)
    mtxt = open(MACROS).read()
    pt = re.search(r'\\newcommand\{\\ParamsTrain\}\{([\d{},]+)\}', mtxt).group(1)
    assert int(re.sub(r'\D', '', pt)) == params, (pt, params)

    C, G = cpu['cells'], gpu['cells']
    assert [cell_tex(C[s]['cell']) for s, _ in SIZES] == [
        '$10$, $1$, $0.6$', '$20$, $1$, $0.6$', '$50$, $2$, $1.0$',
        '$80$, $3$, $1.0$'], 'cells differ from those named in the table note'
    for s, _ in SIZES:
        assert C[s]['cell'] == G[s]['cell'] and C[s]['events_mean'] == G[s]['events_mean']

    out = []

    def macro(name, value, note):
        out.append(f'\\newcommand{{\\{name}}}{{{value}}}  % {note}')

    f1 = lambda x: f'{x:.1f}'
    mib = lambda kb: kb / 1024
    for s, w in SIZES:
        macro(f'LatEvtCpu{w}', f1(C[s]['event']['mean_ms']),
              f'ms per event incl. env.step, CPU, {C[s]["cell"]}, mean of '
              f'{C[s]["event"]["n"]} events ({C[s]["event"]["mean_ms"]:.3f})')
    for s, w in (('10', 'Ten'), ('80', 'Eighty')):
        macro(f'LatEvtGpu{w}', f1(G[s]['event']['mean_ms']),
              f'same on the GPU ({G[s]["event"]["mean_ms"]:.3f})')
        macro(f'LatFwdCpu{w}', f1(C[s]['fwd']['mean_ms']),
              f'ms forward + greedy selection only, CPU ({C[s]["fwd"]["mean_ms"]:.3f})')
    gf = [G[s]['fwd']['mean_ms'] for s, _ in SIZES]
    macro('LatFwdGpuMin', f1(min(gf)), f'ms forward + selection, GPU, min over sizes ({min(gf):.3f})')
    macro('LatFwdGpuMax', f1(max(gf)), f'same, max ({max(gf):.3f})')
    for s, w in (('10', 'Ten'), ('80', 'Eighty')):
        macro(f'LatSchedCpu{w}', f1(C[s]['end_to_end_s_mean']),
              f's per instance end to end, CPU ({C[s]["end_to_end_s_mean"]:.3f})')
    macro('LatSchedGpuEighty', f1(G['80']['end_to_end_s_mean']),
          f's per instance end to end, GPU ({G["80"]["end_to_end_s_mean"]:.3f})')
    rc = [mib(C[s]['ru_maxrss_kb']) for s, _ in SIZES]
    rg = [mib(G[s]['ru_maxrss_kb']) for s, _ in SIZES]
    ri = [mib(d['cells'][s]['rss_after_import_kb']) for d in (cpu, gpu) for s, _ in SIZES]
    macro('PeakRssCpuMin', f'{min(rc):.0f}', f'MiB, ru_maxrss of the CPU cell process, min over sizes ({min(rc):.1f})')
    macro('PeakRssCpuMax', f'{max(rc):.0f}', f'same, max ({max(rc):.1f})')
    macro('PeakRssGpuMin', f'{min(rg):,.0f}'.replace(',', '{,}'),
          f'MiB, ru_maxrss of the GPU cell process, min over sizes ({min(rg):.1f})')
    macro('PeakRssGpuMax', f'{max(rg):,.0f}'.replace(',', '{,}'),
          f'MiB, ru_maxrss of the GPU cell process, max over sizes ({max(rg):.1f})')
    macro('RssImport', f'{min(ri):.0f}', f'MiB, RSS after importing torch, min over cells and passes ({min(ri):.1f}; max {max(ri):.1f})')
    ca = max(r.get('cuda_max_allocated_bytes') or 0 for c in G.values()
             for sd in c['seeds'].values() for r in sd['rows'].values())
    macro('CudaAllocMax', f1(ca / 2**20), f'MiB, torch peak allocated GPU memory, max over instances ({ca} B)')
    macro('CkptBytes', f'{nbytes:,}'.replace(',', '{,}'), 'size-mixture checkpoint file, bytes (same for seeds 301-303)')
    macro('CkptKiB', f'{nbytes / 1024:.0f}', f'same in KiB ({nbytes / 1024:.2f})')

    rows = []
    for s, _ in SIZES:
        c, g = C[s], G[s]
        rows.append(' & '.join([
            f'${s}$', f'{c["events_mean"]:,.0f}'.replace(',', '{,}'),
            f1(c['event']['mean_ms']), f1(c['event']['p95_ms']),
            f1(g['event']['mean_ms']), f1(g['event']['p95_ms']),
            f1(c['end_to_end_s_mean']), f1(g['end_to_end_s_mean']),
            f'{mib(c["ru_maxrss_kb"]):.0f}',
        ]) + r' \\')

    mblock = '\n'.join([BEGIN,
                        f'% Sources: {CPU}, {GPU} (commit {cpu["git"]["commit"][:7]};',
                        f'% CPU pass {cpu["started"]}, GPU pass {gpu["started"]}; core {cpu["cores"]}).',
                        *out, END]) + '\n'
    tblock = BEGIN + '\n' + '\n'.join(rows) + '\n' + END
    print(mblock)
    print(tblock)
    if WRITE:
        if BEGIN in mtxt:
            i, j = mtxt.index(BEGIN), mtxt.index(END) + len(END) + 1
            mtxt = mtxt[:i] + mblock + mtxt[j:]
        else:
            mtxt = mtxt.rstrip('\n') + '\n\n' + mblock
        open(MACROS, 'w').write(mtxt)
        s = open(SUPP).read()
        i, j = s.index(BEGIN), s.index(END) + len(END)
        open(SUPP, 'w').write(s[:i] + tblock + s[j:])
        print(f'patched {MACROS} and {SUPP}')


if __name__ == '__main__':
    main()
