"""Seed-level inference for the headline comparisons.

The manuscript's tests average the three training seeds (301/302/303) per
instance and then test over instances (paired Wilcoxon, Holm), so training
seed variation enters the reported numbers but not the reported p-values.
This script answers that from the stored per-seed per-instance results,
for every headline comparison:

  (1) per seed: the mean relative difference, W/T/L and the paired Wilcoxon
      p of that training seed alone, with the sidedness of the manuscript's
      own test for the comparison;
  (2) a two-level bootstrap 95% percentile interval of the mean relative
      difference. Each replicate draws three training seeds with replacement
      and then the instances with replacement. One instance draw per
      replicate is shared by the drawn seeds and by the comparator, so the
      pairing of the two arms on an instance and the crossing of seeds with
      instances are kept. When both arms are learned, the seeds of each arm
      are drawn independently, since each seed is a separate training run of
      that arm. 10,000 replicates, numpy Generator seeded 20261008, rows
      drawn in the fixed order below. Also reported: the share of
      replicates whose relative difference has the sign of the point
      estimate;
  (3) a seed-blocked sign statement: how many of the three seeds share the
      sign of the point estimate, and whether the interval excludes zero.

Comparisons, data and sign convention (positive = the first-named arm, the
manuscript's method, is shorter):
  grid    Table II. BOLT (m1-bcb-guide) vs the best dispatching pair per cell
          (lowest cell mean of the nine pairs, as scripts/fill_macros.py
          selects it), nine cells |V| in {1,2,3} x tau/p in {0.3,0.6,1.0},
          n=100. rel = (PDR - BOLT)/PDR. One-sided Wilcoxon (BOLT shorter).
          Inputs test_results/PPVCT/{cell}/Result_greedy+...-s{s}_{cell}.npy,
          results/pdr/10x25+ppvct-mixed+{cell}.json.
  prodpdr Table III. Size-mixture policy (m1-bcb-guide-mix) vs the best
          fixed pair, three production cells, n=20. rel = (PDR - policy)/PDR.
          Two-sided Wilcoxon, as scripts/x2_production_macros.py.
  prodcp  Table III. Same policy vs the CP-SAT 3600-s incumbent on the two
          cells where the policy is shorter (50/2/1.0 and 80/3/1.0).
          rel = (CP - policy)/CP. Two-sided Wilcoxon. (The manuscript's
          \\ScCpNoMatchDef divides by the policy instead; it is checked
          separately below.)
  ablgrid Table S-VII. BOLT vs the same arm without B_veh
          (m1-bcb-guide-noveh), the two pre-specified cells v1+t0.6 and
          v1+t1.0, n=100. rel = (no-veh - BOLT)/BOLT. One-sided Wilcoxon.
  ablmix  Table S-VIII. Size-mixture policy vs its retrained no-B_veh arm,
          three production cells, n=20. rel = (no-veh - mixture)/mixture.
          One-sided Wilcoxon.
  ladder  Table S-VI. Price channel (m1-bcb-guide) vs the credit-only arm
          (m1-bcb), four pre-specified gate cells, n=100.
          rel = (credit-only - price)/credit-only. One-sided Wilcoxon.
For the ablation and ladder rows the per-seed result pairs seed s of one arm
with seed s of the other, as the per-seed columns of Tables S-VII/S-VIII do.

Check: every seed-mean statistic the manuscript prints for these rows
(macros.tex, and the per-seed columns of Tables S-VII and S-VIII) is
recomputed from the same files and asserted equal at the printed precision.

Usage:
  python scripts/x2_seed_level_inference.py           # print only
  python scripts/x2_seed_level_inference.py --write   # also append the macro
      block to macros.tex and write the paragraph and table between
      '% >>> tab:seedlevel' and '% <<< tab:seedlevel' in supplementary.tex
      (the markers must already exist there)
"""
import json
import os
import re
import sys

import numpy as np
from scipy.stats import wilcoxon

WRITE = '--write' in sys.argv
MACROS = 'paper/main_manuscript_bundle/macros.tex'
SUPP = 'paper/main_manuscript_bundle/supplementary.tex'
TAG = 'generated by scripts/x2_seed_level_inference.py'
SEEDS = (301, 302, 303)
TOL = 1e-6
R = 10_000
RNG_SEED = 20261008
MIX = 'mix10-15-20x25+ppvct-mixed+m1-bcb-guide-mix'
NOVEH_MIX = 'mix10-15-20x25+ppvct-mixed+m1-bcb-guide-mix-noveh'
GRID9 = [(f'v{v}+t{t}', f'V{fw}T{rw}')
         for v, fw in ((1, 'One'), (2, 'Two'), (3, 'Three'))
         for t, rw in (('0.3', 'Three'), ('0.6', 'Six'), ('1.0', 'Ten'))]
PROD = [('50x25+ppvct-mixed+v2+t0.6', 'FiftyTSix', ('50', '2', '0.6')),
        ('50x25+ppvct-mixed+v2+t1.0', 'FiftyTTen', ('50', '2', '1.0')),
        ('80x25+ppvct-mixed+v3+t1.0', 'Eighty', ('80', '3', '1.0'))]
GATE = [('v1+t0.3', 'VOneTThree'), ('v2+t0.3', 'VTwoTThree'),
        ('v1+t0.6', 'VOneTSix'), ('v2+t0.6', 'VTwoTSix')]
GROUPS = {'grid': 'BOLT vs best dispatching pair, 10 modules (Table II)',
          'prodpdr': 'Size-mixture policy vs best dispatching pair (Table III)',
          'prodcp': 'Size-mixture policy vs CP-SAT 3600 s (Table III)',
          'ablgrid': 'BOLT vs no fleet term, 10 modules (Table S-VII)',
          'ablmix': 'Size-mixture policy vs no fleet term (Table S-VIII)',
          'ladder': 'Price channel vs credit-only arm (Table S-VI)'}


# ------------------------------------------------------------------ inputs
def macro_values():
    s = open(MACROS).read()
    return {m.group(1): m.group(2) for m in
            re.finditer(r'^\\newcommand\{\\(\w+)\}\{(.*?)\}(?:\s*%.*)?$', s, re.M)}


def grid_seeds(arm, cell):
    """(3, n) per-seed per-instance makespans of a 10-module arm on a grid cell."""
    out = []
    for s in SEEDS:
        p = f'test_results/PPVCT/{cell}/Result_greedy+10x25+ppvct-mixed+{arm}-s{s}_{cell}.npy'
        if not os.path.exists(p):
            return None
        out.append(np.load(p)[:, 0])
    return np.array(out)


def grid_pdr(cell):
    """Best fixed pair per cell, selected as scripts/fill_macros.py does."""
    data = json.load(open(f'results/pdr/10x25+ppvct-mixed+{cell}.json'))
    pairs = sorted(next(iter(data.values())).keys())
    arr = {q: np.array([d[q] for d in data.values()]) for q in pairs}
    best = min(arr, key=lambda q: arr[q].mean())
    return arr[best], best


def prod_seeds(arm, cell, root):
    """(instance names, (3, n) makespans) of a production-cell arm."""
    rows = []
    for s in SEEDS:
        p = f'{root}/{arm}-s{s}_{cell}.json'
        if not os.path.exists(p):
            return None, None
        rows.append(json.load(open(p))['rows'])
    names = sorted(rows[0])
    assert all(sorted(r) == names for r in rows), f'{cell}: instance sets differ across seeds'
    return names, np.array([[r[i]['ms'] for i in names] for r in rows])


def prod_pdr(cell, names):
    pdr = json.load(open(f'results/scaleup/pdr/{cell}.json'))
    assert sorted(pdr) == names, f'{cell}: PDR instances differ'
    pairs = sorted({k for i in names for k in pdr[i]})
    best = min(pairs, key=lambda k: np.mean([pdr[i][k] for i in names]))
    return np.array([pdr[i][best] for i in names]), best


def prod_cp(cell, names):
    rows = {}
    for line in open(f'results/scaleup/cpsat_b/{cell}.jsonl'):
        if line.strip():
            r = json.loads(line)
            rows[r['instance']] = r
    assert sorted(rows) == names, f'{cell}: CP-SAT ledger incomplete'
    return np.array([rows[i]['ub'] for i in names])


def table_seed_columns(label, nkey):
    """Per-seed strings of the supplement table with the given label, keyed
    by the row's leading cells (as printed)."""
    s = open(SUPP).read()
    k = s.index(f'\\label{{{label}}}')
    body = s[k:s.index('\\end{tabular}', k)]
    out = {}
    for line in body.splitlines():
        cells = [c.strip() for c in line.rstrip('\\ ').split('&')]
        if len(cells) >= 5 and cells[-1].count('$') == 6:
            key = tuple(re.sub(r'\\tnote\{\w\}|\$', '', c) for c in cells[:nkey])
            out[key] = [c.strip('$ ') for c in cells[-1].split(',')]
    return out


# -------------------------------------------------------------- statistics
def ms(x):
    return f'{x.mean():.1f}$\\pm${x.std(ddof=1):.1f}'


def wtl(a, b):
    d = np.asarray(a) - np.asarray(b)
    w, l = int((d < -TOL).sum()), int((d > TOL).sum())
    return f'{w}/{len(d) - w - l}/{l}'


def rel(a, b, denom):
    """Relative difference in %, positive when arm a is shorter than b."""
    a, b = np.mean(a), np.mean(b)
    return 100.0 * (b - a) / (b if denom == 'b' else a)


def fmt1(x):
    return f'{x:+.1f}'.replace('-0.0', '0.0').replace('+0.0', '0.0')


class Row:
    """One comparison x cell: arm a (3 seeds) against comparator b (fixed or 3 seeds)."""

    def __init__(self, group, cell, label, a, b, denom, alt):
        self.group, self.cell, self.label = group, cell, label
        self.a, self.b, self.denom, self.alt = a, b, denom, alt
        self.b_seeded = b.ndim == 2
        abar = a.mean(0)
        bbar = b.mean(0) if self.b_seeded else b
        self.abar, self.bbar = abar, bbar
        self.point = rel(abar, bbar, denom)
        self.wtl = wtl(abar, bbar)
        self.per_seed = []
        for k in range(len(SEEDS)):
            bs = b[k] if self.b_seeded else b
            p = (wilcoxon(a[k], bs, alternative=alt).pvalue
                 if np.any(np.abs(a[k] - bs) > TOL) else 1.0)
            self.per_seed.append((rel(a[k], bs, denom), wtl(a[k], bs), p))

    def bootstrap(self, rng):
        n = self.a.shape[1]
        si = rng.integers(0, len(SEEDS), (R, len(SEEDS)))
        sj = rng.integers(0, len(SEEDS), (R, len(SEEDS))) if self.b_seeded else None
        ii = rng.integers(0, n, (R, n))
        am = self.a[si[:, :, None], ii[:, None, :]].mean((1, 2))
        bm = (self.b[sj[:, :, None], ii[:, None, :]].mean((1, 2)) if self.b_seeded
              else self.b[ii].mean(1))
        reps = 100.0 * (bm - am) / (bm if self.denom == 'b' else am)
        self.ci = tuple(np.percentile(reps, [2.5, 97.5]))
        self.share = float(np.mean(np.sign(reps) == np.sign(self.point)))
        self.agree = sum(np.sign(r) == np.sign(self.point) for r, _, _ in self.per_seed)
        self.excl0 = self.ci[0] > 0 or self.ci[1] < 0


# ------------------------------------------------------------------ build
def build(M):
    rows, missing = [], []
    checks = []

    def check(what, got, want):
        checks.append(what)
        assert got == want, f'{what}: recomputed {got!r}, manuscript prints {want!r}'

    # (a) grid, Table II
    for cell, suff in GRID9:
        a = grid_seeds('m1-bcb-guide', cell)
        if a is None:
            missing.append(f'grid {cell}')
            continue
        b, pair = grid_pdr(cell)
        r = Row('grid', cell, f'{cell[1]}, {cell[4:]}', a, b, 'b', 'less')
        check(f'qOurs{suff}', ms(r.abar), M[f'qOurs{suff}'])
        check(f'qPdr{suff}', ms(b), M[f'qPdr{suff}'])
        check(f'qWtl{suff}', r.wtl, M[f'qWtl{suff}'])
        r.note = pair
        rows.append(r)
    # (b) production batches, Table III
    for cell, suff, (mo, v, t) in PROD:
        names, a = prod_seeds(MIX, cell, 'results/scaleup/policy')
        if a is None:
            missing.append(f'prodpdr {cell}')
            continue
        b, pair = prod_pdr(cell, names)
        r = Row('prodpdr', cell, f'{mo}, {v}, {t}', a, b, 'b', 'two-sided')
        check(f'ScMix{suff}', ms(r.abar), M[f'ScMix{suff}'])
        check(f'ScMixDPdr{suff}', f'{r.point:.1f}', M[f'ScMixDPdr{suff}'])
        check(f'ScMixWtl{suff}', r.wtl, M[f'ScMixWtl{suff}'])
        r.note = pair
        rows.append(r)
    for cell, suff, (mo, v, t) in PROD[1:]:
        names, a = prod_seeds(MIX, cell, 'results/scaleup/policy')
        cp = prod_cp(cell, names)
        r = Row('prodcp', cell, f'{mo}, {v}, {t}', a, cp, 'b', 'two-sided')
        if suff == 'Eighty':
            check('ScMixDCpEighty', f'{r.point:.1f}', M['ScMixDCpEighty'])
            check('ScMixWtlCpEighty', r.wtl, M['ScMixWtlCpEighty'])
        else:
            check('ScCpNoMatchDef', f'{rel(r.abar, cp, "a"):.1f}', M['ScCpNoMatchDef'])
            check('ScMixWtlCpFifty', r.wtl, M['ScMixWtlCpFifty'])
        r.note = 'CP-SAT 3600 s'
        rows.append(r)
    # (c) fleet-term ablation
    s7 = table_seed_columns('tab:noveh', 2)
    for cell, suff in (('v1+t0.6', 'VOneTSix'), ('v1+t1.0', 'VOneTTen')):
        a, b = grid_seeds('m1-bcb-guide', cell), grid_seeds('m1-bcb-guide-noveh', cell)
        if a is None or b is None:
            missing.append(f'ablgrid {cell}')
            continue
        r = Row('ablgrid', cell, f'{cell[1]}, {cell[4:]}', a, b, 'a', 'less')
        check(f'AblVehD{suff}', f'{r.point:.1f}', M[f'AblVehD{suff}'])
        check(f'AblVehWtl{suff}', r.wtl, M[f'AblVehWtl{suff}'])
        check(f'Table S-VII per seed {cell}', [fmt1(x) for x, _, _ in r.per_seed],
              s7[(cell[1], cell[4:])])
        r.note = 'no B_veh'
        rows.append(r)
    s8 = table_seed_columns('tab:novehmix', 3)
    for cell, suff, (mo, v, t) in PROD:
        names, a = prod_seeds(MIX, cell, 'results/scaleup/policy')
        nb, b = prod_seeds(NOVEH_MIX, cell, 'results/ablation/noveh_mix/policy')
        if a is None or b is None:
            missing.append(f'ablmix {cell}')
            continue
        assert nb == names, f'{cell}: ablation instances differ'
        r = Row('ablmix', cell, f'{mo}, {v}, {t}', a, b, 'a', 'less')
        check(f'AblVehMixD{suff}', f'{r.point:.1f}', M[f'AblVehMixD{suff}'])
        check(f'AblVehMixWtl {cell}', r.wtl, M['AblVehMixWtl'])
        check(f'Table S-VIII per seed {cell}', [fmt1(x) for x, _, _ in r.per_seed],
              s8[(mo, v, t)])
        r.note = 'no B_veh'
        rows.append(r)
    # (d) action-price ladder, Table S-VI
    for cell, suff in GATE:
        a, b = grid_seeds('m1-bcb-guide', cell), grid_seeds('m1-bcb', cell)
        if a is None or b is None:
            missing.append(f'ladder {cell}')
            continue
        r = Row('ladder', cell, f'{cell[1]}, {cell[4:]}', a, b, 'b', 'less')
        check(f'GuImp{suff}', f'{r.point:+.2f}', M[f'GuImp{suff}'])
        check(f'GuWtl{suff}', r.wtl, M[f'GuWtl{suff}'])
        check(f'LadGuide{suff}', ms(r.abar), M[f'LadGuide{suff}'])
        check(f'LadCredit{suff}', ms(r.bbar), M[f'LadCredit{suff}'])
        r.note = 'credit-only'
        rows.append(r)
    return rows, missing, checks


# ----------------------------------------------------------------- output
def tex_ci(ci):
    """Interval with one decimal, or two when a bound would print as 0.0."""
    lo, hi = ci
    f = (lambda x: f'{x:+.2f}') if min(abs(lo), abs(hi)) < 0.05 else fmt1
    return f'[{f(lo)}, {f(hi)}]'


def cell_word(cell):
    w = {'1': 'One', '2': 'Two', '3': 'Three', '0.3': 'TThree', '0.6': 'TSix', '1.0': 'TTen'}
    if cell.startswith('v'):
        return f'V{w[cell[1]]}{w[cell[4:]]}'
    return {'50x25+ppvct-mixed+v2+t0.6': 'FiftyTSix', '50x25+ppvct-mixed+v2+t1.0': 'FiftyTTen',
            '80x25+ppvct-mixed+v3+t1.0': 'Eighty'}[cell]


def summary_macros(rows):
    n = len(rows)
    agree3 = [r for r in rows if r.agree == 3]
    excl = [r for r in rows if r.excl0]
    pp = [r for r in rows if r.group == 'prodpdr']
    m = [('SeedRowsN', str(n), 'comparison x cell rows of tab:seedlevel'),
         ('SeedAgreeRows', str(len(agree3)),
          'rows in which all three training seeds share the sign of the seed-mean difference'),
         ('SeedAgreeAll', 'every headline comparison' if len(agree3) == n
          else f'{len(agree3)} of the {n} headline comparison cells',
          'text form of SeedAgreeRows'),
         ('BootExclZeroRows', str(len(excl)),
          'rows whose two-level bootstrap 95% interval excludes zero'),
         ('BootCiProdPdrMin', f'{min(r.ci[0] for r in pp):.1f}',
          'smallest lower 95% bound, size-mixture policy vs best pair, three production cells, % of PDR'),
         ('BootCiProdPdrMax', f'{max(r.ci[1] for r in pp):.1f}', 'largest upper 95% bound, same rows'),
         ('BootSignShareMin', f'{100 * min(r.share for r in rows):.1f}',
          'smallest share (%) of bootstrap replicates with the sign of the seed-mean difference, all rows'),
         ('BootReps', '10{,}000', f'bootstrap replicates per row, numpy Generator seeded {RNG_SEED}')]
    for r in rows:
        if r.agree < 3 or not r.excl0:
            m.append((f'BootCi{r.group.capitalize()}{cell_word(r.cell)}',
                      f'\\ensuremath{{{tex_ci(r.ci)}}}',
                      f'two-level bootstrap 95% interval in %, {r.group} {r.cell}, '
                      f'seeds agreeing {r.agree}/3'))
    return m


# Rows the paragraph below names as weaker. The text is written for exactly
# this set, so a change in the data stops --write until the text is revised.
WEAK = {('grid', 'v1+t1.0'): 'seed', ('ablgrid', 'v1+t1.0'): 'seed',
        ('prodcp', '50x25+ppvct-mixed+v2+t1.0'): 'seed',
        ('grid', 'v1+t0.3'): 'ci', ('grid', 'v3+t1.0'): 'ci'}


def paragraph(rows):
    by = {(r.group, r.cell): r for r in rows}
    weak = {k: ('seed' if r.agree < 3 else 'ci') for k, r in by.items()
            if r.agree < 3 or not r.excl0}
    assert weak == WEAK, f'weaker rows changed, revise the paragraph text: {weak}'
    strong = [g for g in GROUPS if all((g, r.cell) not in weak for r in rows if r.group == g)]
    assert strong == ['prodpdr', 'ablmix', 'ladder'], strong
    g10, a10 = by[('grid', 'v1+t1.0')], by[('ablgrid', 'v1+t1.0')]
    cp = by[('prodcp', '50x25+ppvct-mixed+v2+t1.0')]
    g03, g31 = by[('grid', 'v1+t0.3')], by[('grid', 'v3+t1.0')]
    neg = lambda r: [(s, -x) for s, (x, _, _) in zip(SEEDS, r.per_seed) if x < 0]
    (sg, xg), = neg(g10)
    (sa, xa), = neg(a10)
    (sc, xc), = neg(cp)
    assert sg == sa
    return (
        f'Each training seed alone favors the same arm as the seed mean in '
        f'\\SeedAgreeRows{{}} of the \\SeedRowsN{{}} headline comparison cells '
        f'(Table~\\ref{{tab:seedlevel}}). The tests of the main text average the '
        f'makespans of the three seeds per instance, so their $p$-values reflect instance variation '
        f'only. A two-level bootstrap adds the seed variation. Each of its '
        f'\\BootReps{{}} replicates draws three seeds with replacement and then '
        f'the instances. The resulting 95\\% interval excludes zero in '
        f'\\BootExclZeroRows{{}} cells. On the production batches, every seed '
        f'of the size-mixture policy is shorter on average than the best '
        f'dispatching pair, '
        f'with interval bounds from $+\\BootCiProdPdrMin\\%$ to '
        f'$+\\BootCiProdPdrMax\\%$. The fleet-term ablation on production '
        f'batches and the price channel on the four gate cells also hold for '
        f'every seed, and their intervals exclude zero. In three cells, one seed '
        f'favors the other arm. At one vehicle and $\\bar\\tau/\\bar p=1.0$, a '
        f'travel intensity outside training, seed {sg} of BOLT is {xg:.1f}\\% '
        f'longer than the best pair. The ablation without $\\Bveh$ trained with '
        f'seed {sa} is {xa:.1f}\\% shorter than that BOLT seed. '
        f'At 50 modules, two vehicles and $\\bar\\tau/\\bar p=1.0$, seed {sc} '
        f'of the size-mixture policy is {xc:.1f}\\% longer than the CP-SAT '
        f'3600-s incumbent. The intervals of these three cells include zero. '
        f'In two further grid cells, every seed favors BOLT, but the intervals '
        f'include zero. Their mean margins are {g03.point:.1f}\\% at one vehicle '
        f'with $\\bar\\tau/\\bar p=0.3$ and {g31.point:.1f}\\% at three '
        f'vehicles with $\\bar\\tau/\\bar p=1.0$. With three '
        f'seeds, the seed level of the bootstrap has only ten distinct draws, so '
        f'the intervals are approximate.')


def table_tex(rows):
    lines = [paragraph(rows), '',
             '\\begin{table}[htbp]', '\\centering',
             '\\caption{Relative makespan difference of each training seed alone, '
             'number of seeds with the sign of the seed mean, and two-level '
             'bootstrap 95\\% interval for the headline comparisons. The interval '
             'resamples training seeds and then instances. Positive values favor '
             'the first-named arm.}',
             '\\label{tab:seedlevel}', '\\begin{threeparttable}', '\\footnotesize',
             '\\setlength{\\tabcolsep}{2.6pt}',
             '\\begin{tabular}{@{}lrrrccr@{}}', '\\toprule',
             '& \\multicolumn{3}{c}{Per seed (\\%)} & & 95\\% interval & Same \\\\',
             '\\cmidrule(lr){2-4}',
             'Cell & 301 & 302 & 303 & Agree & (\\%) & sign (\\%) \\\\',
             '\\midrule']
    first = True
    for g, title in GROUPS.items():
        rs = [r for r in rows if r.group == g]
        if not rs:
            continue
        if not first:
            lines.append('\\addlinespace[2pt]')
        first = False
        lines.append(f'\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title.replace(" vs ", " vs.~")}}}}} \\\\')
        for r in rs:
            seeds = ' & '.join(f'${fmt1(x)}$' for x, _, _ in r.per_seed)
            lines.append(f'{r.label} & {seeds} & {r.agree}/3 & ${tex_ci(r.ci)}$ & '
                         f'{100 * r.share:.1f} \\\\')
    lines += [
        '\\bottomrule', '\\end{tabular}', '\\begin{tablenotes}\\footnotesize',
        '\\item Cell: $|V|$ and $\\bar\\tau/\\bar p$ at 10 modules ($n=100$), or '
        'modules, $|V|$ and $\\bar\\tau/\\bar p$ for production batches ($n=20$). '
        'The difference is taken in percent of the dispatching pair, the CP-SAT '
        'incumbent or the credit-only arm, and of the arm with the fleet term in '
        'the ablation rows. Same sign: share of the \\BootReps{} replicates with '
        'the sign of the seed-mean difference.',
        '\\end{tablenotes}', '\\end{threeparttable}', '\\end{table}']
    return '\n'.join(lines) + '\n'


def report(rows):
    for g, title in GROUPS.items():
        print(f'\n{title}')
        for r in (x for x in rows if x.group == g):
            ps = '  '.join(f's{s}: {x:+6.2f}% {w:>8s} p={p:.1e}'
                           for s, (x, w, p) in zip(SEEDS, r.per_seed))
            print(f'  {r.cell:27s} [{r.note}] mean {r.point:+6.2f}% {r.wtl:>8s} | {ps}')
            print(f'  {"":27s} agree {r.agree}/3  CI95 [{r.ci[0]:+.2f}, {r.ci[1]:+.2f}]  '
                  f'same-sign {100 * r.share:.1f}%  {"excludes 0" if r.excl0 else "INCLUDES 0"}')
    sig = sum(p < 0.05 for r in rows for _, _, p in r.per_seed)
    print(f'\nper-seed Wilcoxon p < 0.05 (uncorrected, sidedness of each comparison): '
          f'{sig} of {3 * len(rows)} seed tests')


def replace_markers(path, body):
    s = open(path).read()
    pat = re.compile(r'(% >>> tab:seedlevel\n).*?(% <<< tab:seedlevel)', re.S)
    if not pat.search(s):
        sys.exit(f'refusing --write: no tab:seedlevel markers in {path}')
    s = pat.sub(lambda m: m.group(1) + f'% {TAG}\n' + body + m.group(2), s, count=1)
    open(path, 'w').write(s)
    print(f'patched {path}')


def write_macros(m):
    s = open(MACROS).read()
    body = ('% Seed-level inference for the headline comparisons: per-seed relative\n'
            '% differences and a two-level bootstrap (training seeds, then instances)\n'
            f'% of the seed-mean relative difference, {R} replicates, seed {RNG_SEED}.\n'
            '% Inputs: test_results/PPVCT, results/pdr, results/scaleup/{policy,pdr,cpsat_b},\n'
            '% results/ablation/noveh_mix (conventions in the script docstring).\n'
            + ''.join(f'\\newcommand{{\\{k}}}{{{v}}}  % {c}\n' for k, v, c in m))
    pat = re.compile(r'(% BEGIN ' + re.escape(TAG) + r'\n).*?(% END ' + re.escape(TAG) + r')', re.S)
    if pat.search(s):
        s = pat.sub(lambda x: x.group(1) + body + x.group(2), s, count=1)
    else:
        s = s.rstrip('\n') + f'\n\n% BEGIN {TAG}\n{body}% END {TAG}\n'
    open(MACROS, 'w').write(s)
    print(f'patched {MACROS}')


def main():
    M = macro_values()
    rows, missing, checks = build(M)
    print(f'reproduced {len(checks)} printed statistics at the printed precision')
    if missing:
        print('per-seed data not on disk, skipped:', ', '.join(missing))
    rng = np.random.default_rng(RNG_SEED)
    for r in rows:
        r.bootstrap(rng)
    report(rows)
    m = summary_macros(rows)
    print('\n% ---- macros ----')
    for k, v, c in m:
        print(f'\\newcommand{{\\{k}}}{{{v}}}  % {c}')
    print('\n% ---- supplement block ----')
    print(table_tex(rows))
    if WRITE:
        if missing:
            sys.exit('refusing --write: per-seed data missing')
        write_macros(m)
        replace_markers(SUPP, table_tex(rows))


if __name__ == '__main__':
    main()
