"""Short-travel production cells: one vehicle, travel ratio 0.3, 50 and 80 modules.

Report and macros for the cells 50x25+ppvct-mixed+v1+t0.3 and
80x25+ppvct-mixed+v1+t0.3 (results/shorttravel/{pdr,ga,policy}/), with the
conventions of scripts/x2_production_macros.py: makespans in hours as mean
$\\pm$ sample standard deviation (ddof=1) over the 20 instances; a learned
arm's value on an instance is the mean over training seeds 301/302/303;
win/tie/loss with ties at 1e-6; paired Wilcoxon signed-rank; relative
differences in percent of the arm named in the provenance comment. The best
fixed pair is the single PDR pair with the lowest mean over the cell's
instances.

Minimum loaded utilization follows scripts/x2_util_extended.py:
u = W_tr / (|V| C), W_tr the root B_veh at |V|=1 per instance (mean over the
cell's instances), C the best known mean makespan over every arm that ran
the cell (best fixed pair, GA-60, each learned arm's 3-seed per-instance
means). No schedule is needed; empty legs are excluded, so u is a floor.

Penalty anchor: 10x25+ppvct-mixed+e0b-uncontended-s301 (one seed), deployed
as in the main comparison: its machine head
decides and the nearest-vehicle-first rule makes every vehicle decision,
because its vehicle head is masked from the loss in training and is
untrained. Files: results/shorttravel/policy/<anchor>+nvf_<cell>.json, from
scripts/eval_ppvct.py --veh_rule NVF on one CPU thread. A run that lets
the untrained vehicle head decide is not valid and is not part of the
released results.
Relative differences against the anchor: (anchor - arm)/anchor in percent,
positive when the arm is shorter.

Merged against factorized heads (both size-mixture arms): the paired +-2%
equivalence test of scripts/stats_tost.py with its fixed bootstrap seed, as
in scripts/x2_single_vs_marl_mix.py (Table S-XII): per-instance relative
difference (factorized - merged)/merged in percent, 90% bootstrap CI,
verdict per the 2026-08-17 rule.

With --write the script also rewrites the rows of the supplement table
tab:shorttravel between its BEGIN/END marker comments in
paper/main_manuscript_bundle/supplementary.tex.

Usage:
  python scripts/x2_shorttravel_report.py            # print the report
  python scripts/x2_shorttravel_report.py --write    # also write the macros
"""
import glob
import json
import os
import re
import sys

WRITE = '--write' in sys.argv
sys.argv = [sys.argv[0]]
import numpy as np
from scipy.stats import wilcoxon

sys.path.insert(0, '.')

MACROS = 'paper/main_manuscript_bundle/macros.tex'
RES = 'results/shorttravel'
MIX = 'mix10-15-20x25+ppvct-mixed+m1-bcb-guide-mix'
TEN = '10x25+ppvct-mixed+m1-bcb-guide'
MER = 'mix10-15-20x25+ppvct-mixed+single-joint-mix'
PEN = '10x25+ppvct-mixed+e0b-uncontended-s301+nvf'
SUPP = 'paper/main_manuscript_bundle/supplementary.tex'
TROWS_BEGIN = '% BEGIN rows generated by scripts/x2_shorttravel_report.py'
TROWS_END = '% END rows generated by scripts/x2_shorttravel_report.py'
TRAIN_FLEET, TRAIN_SIZES = (1, 2, 3), (10, 15, 20)
SEEDS = (301, 302, 303)
CELLS = {'FiftyLow': '50x25+ppvct-mixed+v1+t0.3',
         'EightyLow': '80x25+ppvct-mixed+v1+t0.3'}
TOL = 1e-6
BEGIN = '% BEGIN generated by scripts/x2_shorttravel_report.py'
END = '% END generated by scripts/x2_shorttravel_report.py'
sys.path.insert(0, '.')
from scripts.stats_tost import paired_tost


def pm(x):
    x = np.asarray(x, float)
    return f'{x.mean():.1f}$\\pm${x.std(ddof=1):.1f}'


def wtl(a, b):
    d = np.asarray(a) - np.asarray(b)
    w, l = int((d < -TOL).sum()), int((d > TOL).sum())
    return f'{w}/{len(d) - w - l}/{l}'


def pval(a, b):
    p = wilcoxon(np.asarray(a), np.asarray(b)).pvalue
    m, e = f'{p:.1e}'.split('e')
    return f'{m}\\times10^{{{int(e)}}}', p


def pval_plain(a, b):
    """p as a decimal when p >= 0.001, else in the x10^ form of pval()."""
    p = wilcoxon(np.asarray(a), np.asarray(b)).pvalue
    return (f'{p:.2g}' if p >= 1e-3 else pval(a, b)[0]), p


def rel(a, b):
    """(a - b) / b in percent, positive when a is above b."""
    return 100.0 * (np.mean(a) - np.mean(b)) / np.mean(b)


def meta(cell):
    return json.load(open(f'data/PPVCT/{cell}/test/dataset_meta.json'))


def policy(arm, cell):
    ms = []
    for s in SEEDS:
        p = f'{RES}/policy/{arm}-s{s}_{cell}.json'
        if not os.path.exists(p):
            return None, None
        d = json.load(open(p))
        assert all(r.get('validated', True) for r in d['rows'].values()), p
        ms.append({k: v['ms'] for k, v in d['rows'].items()})
    inst = sorted(ms[0])
    assert all(sorted(m) == inst for m in ms), (arm, cell, 'seed files cover different instances')
    return inst, np.array([[m[i] for i in inst] for m in ms]).mean(0)


def arms_on_disk(cell):
    return sorted({os.path.basename(p).split('-s3')[0]
                   for p in glob.glob(f'{RES}/policy/*_{cell}.json')
                   if '+nvf_' not in os.path.basename(p)})


def anchor(cell):
    """Penalty anchor (one seed) with nearest-vehicle-first vehicle decisions."""
    d = json.load(open(f'{RES}/policy/{PEN}_{cell}.json'))
    assert d['veh_rule'] == 'NVF', d['veh_rule']
    assert all(r['validated'] for r in d['rows'].values())
    inst = sorted(d['rows'])
    return inst, np.array([d['rows'][i]['ms'] for i in inst])


def wtr_batch(stems):
    """W_tr per instance = root B_veh at |V|=1 (f_v=0, so B_veh=W_tr)."""
    from params import configs
    configs.device = 'cpu'
    from ppvc_instance_generator import load_instance
    from transport_marl.fjsp_env_transport import FJSPEnvTransport
    from transport_marl.bound import TransportBound
    jls, pts, lags, opt, mct, lay = [], [], [], [], [], []
    for s in stems:
        jl, pt, m = load_instance(s)
        jls.append(np.asarray(jl))
        pts.append(np.asarray(pt, dtype=float))
        lags.append(np.asarray(m['time_lag'], dtype=float))
        opt.append(np.asarray(m['op_type']))
        mct.append(np.asarray(m['mch_type']))
        lay.append(dict(m['transport'], n_vehicles=1))
    env = FJSPEnvTransport(len(jls[0]), pts[0].shape[1], use_lag_features=True)
    env.set_initial_data(jls, pts, lags, opt, mct, lay)
    return TransportBound(env, use_mch=True, use_veh=True)._b_veh()


def mean_wtr(cell):
    stems = sorted(g[:-4] for g in glob.glob(f'data/PPVCT/{cell}/test/instance_*.fjs'))
    W = []
    for i0 in range(0, len(stems), 10):
        W.extend(np.asarray(wtr_batch(stems[i0:i0 + 10])).tolist())
    return float(np.mean(W)), len(W)


def main():
    import torch
    torch.set_num_threads(1)
    out, rows, srows = [], [], []
    cpu_shift = {}

    def macro(name, value, note):
        out.append((name, value, note))

    for tag, cell in CELLS.items():
        md = meta(cell)
        n, V = md['n_instances'], md['n_vehicles']
        src = f'{cell}, n={n}, fixed base seeds (seed0 {md["seed0"]})'
        pdr = json.load(open(f'{RES}/pdr/{cell}.json'))
        inst = sorted(pdr)
        assert len(inst) == n, (cell, len(inst), n)
        pairs = sorted({k for i in inst for k in pdr[i]})
        pair_means = {k: float(np.mean([pdr[i][k] for i in inst])) for k in pairs}
        best_pair = min(pairs, key=pair_means.get)
        best = np.array([pdr[i][best_pair] for i in inst])
        ga = json.load(open(f'{RES}/ga/{cell}.json'))
        assert sorted(ga) == inst, (cell, 'GA instances differ from PDR instances')
        gav = np.array([ga[i]['ga'] for i in inst])
        arms = {}
        for arm in arms_on_disk(cell):
            ii, v = policy(arm, cell)
            if v is not None:
                assert ii == inst, (arm, cell, 'policy instances differ from PDR instances')
                arms[arm] = v
        mix, ten = arms[MIX], arms[TEN]

        # minimum loaded utilization
        W, nw = mean_wtr(cell)
        assert nw == n
        cands = {f'best pair {best_pair}': best.mean(), 'GA-60': gav.mean()}
        cands.update({f'{a} (3-seed mean)': v.mean() for a, v in arms.items()})
        c_src = min(cands, key=cands.get)
        C = float(cands[c_src])
        u = W / (V * C)

        # report
        print(f'\n==== {cell}  (n={n}, |V|={V}) ====')
        print('PDR pair means: ' + ', '.join(f'{k} {pair_means[k]:.1f}'
                                             for k in sorted(pairs, key=pair_means.get)))
        print(f'{"arm":52s} {"mean+-sd":>16s}  vs best pair (%, W/T/L, p)      vs GA-60 (%, W/T/L, p)')
        table = [(f'best fixed pair {best_pair}', best), ('GA-60 (PDR-seeded)', gav)]
        table += [(a, v) for a, v in arms.items()]
        for name, v in table:
            s = f'{name:52s} {v.mean():8.1f}+-{v.std(ddof=1):6.1f}'
            if name.startswith('best fixed'):
                print(s)
                continue
            s += f'  {-rel(v, best):+6.1f} {wtl(v, best):>7s} {pval(v, best)[1]:.1e}'
            if not name.startswith('GA'):
                s += f'   {-rel(v, gav):+6.1f} {wtl(v, gav):>7s} {pval(v, gav)[1]:.1e}'
            print(s)
        print('(relative differences: (rival - arm)/rival in %, positive when the arm is shorter)')
        print(f'GA-60: improved on its PDR seed in {sum(ga[i]["improved_on_seed"] for i in inst)}/{n} '
              f'instances; generations mean {np.mean([ga[i]["gens"] for i in inst]):.1f}')
        print(f'utilization: W_tr mean {W:.1f}, C {C:.1f} from {c_src}, u = {u:.3f}')
        print('C candidates: ' + ', '.join(f'{k} {v:.1f}' for k, v in sorted(cands.items(), key=lambda kv: kv[1])))
        winner = min(cands, key=cands.get)
        print(f'shortest mean in the cell: {winner}')

        # macros
        macro(f'StPdr{tag}', pm(best), f'best fixed pair {best_pair}, {src}')
        macro(f'StGa{tag}', pm(gav), f'PDR-seeded GA, 60 CPU-s of search, {src}')
        macro(f'StMix{tag}', pm(mix), f'size-mixture policy, greedy, per-instance 3-seed means, {src}')
        ps, p = pval(mix, best)
        macro(f'StMixDPdr{tag}', f'{-rel(mix, best):.1f}', f'(PDR - mixture)/PDR in %, best pair {best_pair}, {cell}')
        macro(f'StMixWtl{tag}', wtl(mix, best), f'mixture vs best fixed pair, W/T/L, Wilcoxon p={p:.1e}, {cell}')
        macro(f'StMixP{tag}', ps, f'Wilcoxon, mixture vs best fixed pair, {cell}')
        pg_s, pg = pval(mix, gav)
        macro(f'StMixDGa{tag}', f'{-rel(mix, gav):.1f}',
              f'(GA60 - mixture)/GA60 in %, W/T/L {wtl(mix, gav)}, p={pg:.1e}, {cell}')
        macro(f'StMixWtlGa{tag}', wtl(mix, gav), f'mixture vs GA-60, W/T/L, Wilcoxon p={pg:.1e}, {cell}')
        macro(f'StUtil{tag}', f'{100 * u:.0f}',
              f'u = W_tr/(|V| C) in %, |V|={V}, W_tr={W:.1f}, C={C:.1f} ({c_src}, best known mean), u={u:.3f}')
        bold_pdr = best.mean() < mix.mean()
        cellname = f'${md["n_modules"]}$, ${V}$, ${md["tau_over_p"]}$'
        fp = f'\\StPdr{tag}' if not bold_pdr else f'\\textbf{{\\StPdr{tag}}}'
        fm = f'\\StMix{tag}' if bold_pdr else f'\\textbf{{\\StMix{tag}}}'
        rows.append(f'{cellname} & \\StUtil{tag}\\% & {fp} & {fm} & -- & -- \\\\'
                    f'  % GA-60 \\StGa{tag}; vs best pair W/T/L \\StMixWtl{tag}')
        print(f'10-module price-channel policy ({TEN}): {pm(ten)}; '
              f'vs best pair {-rel(ten, best):+.1f}% W/T/L {wtl(ten, best)} p={pval(ten, best)[1]:.1e}; '
              f'vs GA-60 {-rel(ten, gav):+.1f}% W/T/L {wtl(ten, gav)} p={pval(ten, gav)[1]:.1e}; '
              f'vs mixture {-rel(ten, mix):+.1f}% W/T/L {wtl(ten, mix)}')

        # penalty anchor, merged-head mixture, fleet sparsity
        ia, pen = anchor(cell)
        assert ia == inst, (cell, 'anchor instances differ from PDR instances')
        mer = arms[MER]
        print(f'penalty anchor (NVF, one seed): {pm(pen)}')
        for name, v in [('factorized mixture', mix), ('merged mixture', mer),
                        ('10-module price channel', ten), (f'best pair {best_pair}', best),
                        ('GA-60', gav)]:
            print(f'  {name:26s} vs anchor {-rel(v, pen):+6.1f}%  W/T/L {wtl(v, pen):>7s}  '
                  f'p={pval_plain(v, pen)[1]:.2g}')
        # same-device check: the anchor ran on one CPU thread, the policies on
        # a GPU; the deployed policy re-evaluated on one CPU thread
        # (results/shorttravel/policy_cpu/, x2_scale_policy.py --device cpu)
        cpu = []
        for sd in SEEDS:
            r = json.load(open(f'{RES}/policy_cpu/{MIX}-s{sd}_{cell}cpucheck.json'))
            assert r['device'] == 'cpu' and all(v['validated'] for v in r['rows'].values())
            assert sorted(r['rows']) == inst
            cpu.append([r['rows'][i]['ms'] for i in inst])
        cpu = np.array(cpu, float).mean(0)
        shift = rel(cpu, mix)
        cpu_shift[tag] = shift
        pc_s, pc = pval_plain(cpu, pen)
        print(f'deployed policy on CPU: {pm(cpu)}, {shift:+.2f}% vs its GPU mean; vs anchor '
              f'{rel(cpu, pen):+.1f}% longer, W/T/L {wtl(cpu, pen)}, p={pc:.2g}')
        macro(f'StMixCpuLongPen{tag}', f'{rel(cpu, pen):.1f}',
              f'deployed policy evaluated on one CPU thread: (mixture - anchor)/anchor in %, {cell}')
        macro(f'StMixCpuWtlPen{tag}', wtl(cpu, pen), f'CPU mixture vs anchor, W/T/L, Wilcoxon p={pc:.1e}, {cell}')
        macro(f'StMixCpuPPen{tag}', pc_s, f'Wilcoxon, CPU mixture vs anchor, {cell}')

        t = paired_tost(mix, mer)
        print(f'merged vs factorized (S-XII convention): {t["mean_rel_diff_pct"]:+.2f}% '
              f'[{t["ci90_lo_pct"]:+.2f}, {t["ci90_hi_pct"]:+.2f}] -> {t["verdict"]}, '
              f'factorized W/T/L {t["wtl"]}, Wilcoxon p={t["p_wilcoxon_two_sided"]:.1e}; '
              f'(mix - merged)/mix {100 * (mix.mean() - mer.mean()) / mix.mean():.1f}%')
        vpt = 10.0 * V / md['n_modules']
        vpt_min = 10.0 * min(TRAIN_FLEET) / max(TRAIN_SIZES)
        print(f'vehicles per 10 modules {vpt:g}; trained minimum {vpt_min:g}; '
              f'{vpt_min / vpt:g}x sparser')

        macro(f'StPen{tag}', pm(pen), f'penalty anchor {PEN} (one seed, NVF vehicle rule, CPU), {src}')
        macro(f'StTen{tag}', pm(ten), f'10-module price-channel policy {TEN}, 3-seed means, {src}')
        macro(f'StMer{tag}', pm(mer), f'merged-head size-mixture policy {MER}, 3-seed means, {src}')
        ps_, p_ = pval_plain(mix, pen)
        macro(f'StMixDPen{tag}', f'{-rel(mix, pen):.1f}', f'(anchor - mixture)/anchor in %, {cell}')
        macro(f'StMixWtlPen{tag}', wtl(mix, pen), f'mixture vs penalty anchor, W/T/L, Wilcoxon p={p_:.1e}, {cell}')
        macro(f'StMixPPen{tag}', ps_, f'Wilcoxon, mixture vs penalty anchor, {cell}')
        macro(f'StMixLongPen{tag}', f'{rel(mix, pen):.1f}',
              f'(mixture - anchor)/anchor in %, positive when the mixture is longer, {cell}')
        macro(f'StMixLongPdr{tag}', f'{rel(mix, best):.1f}',
              f'(mixture - PDR)/PDR in %, positive when the mixture is longer, {cell}')
        ps_, p_ = pval_plain(mer, pen)
        macro(f'StMerDPen{tag}', f'{-rel(mer, pen):.1f}', f'(anchor - merged)/anchor in %, {cell}')
        macro(f'StMerWtlPen{tag}', wtl(mer, pen), f'merged vs penalty anchor, W/T/L, Wilcoxon p={p_:.1e}, {cell}')
        macro(f'StMerPPen{tag}', ps_, f'Wilcoxon, merged vs penalty anchor, {cell}')
        ps_, p_ = pval_plain(ten, pen)
        macro(f'StTenDPen{tag}', f'{-rel(ten, pen):.1f}', f'(anchor - 10-module price channel)/anchor in %, {cell}')
        macro(f'StTenLongPen{tag}', f'{rel(ten, pen):.1f}',
              f'(10-module price channel - anchor)/anchor in %, positive when longer, {cell}')
        macro(f'StTenWtlPen{tag}', wtl(ten, pen), f'10-module price channel vs penalty anchor, W/T/L, Wilcoxon p={p_:.1e}, {cell}')
        ps_, p_ = pval_plain(mer, best)
        macro(f'StMerDPdr{tag}', f'{-rel(mer, best):.1f}', f'(PDR - merged)/PDR in %, best pair {best_pair}, {cell}')
        macro(f'StMerWtlPdr{tag}', wtl(mer, best), f'merged vs best fixed pair, W/T/L, Wilcoxon p={p_:.1e}, {cell}')
        macro(f'StMerPPdr{tag}', ps_, f'Wilcoxon, merged vs best fixed pair, {cell}')
        macro(f'MixSaFac{tag}', f'{t["ours_mean"]:.1f}', f'Table S-XII convention, factorized mixture, {cell}')
        macro(f'MixSaMer{tag}', f'{t["single_mean"]:.1f}', f'Table S-XII convention, merged mixture, {cell}')
        macro(f'MixSaRel{tag}', f'{t["mean_rel_diff_pct"]:+.2f}',
              f'(factorized - merged)/merged per instance, mean in %, verdict {t["verdict"]}, {cell}')
        macro(f'MixSaCi{tag}', f'{t["ci90_lo_pct"]:+.2f}, {t["ci90_hi_pct"]:+.2f}',
              f'90% bootstrap CI (scripts/stats_tost.py, fixed seed), {cell}')
        macro(f'MixSaWtl{tag}', t['wtl'], f'factorized vs merged, W/T/L, Wilcoxon p={t["p_wilcoxon_two_sided"]:.1e}, {cell}')
        macro(f'StVehPerTen{tag}', f'{vpt:g}', f'vehicles per 10 modules, |V|={V}, {md["n_modules"]} modules, {cell}')
        if tag == list(CELLS)[0]:
            macro('StVehPerTenTrainMin', f'{vpt_min:g}',
                  f'sparsest trained fleet per 10 modules: |V|={min(TRAIN_FLEET)} at {max(TRAIN_SIZES)} modules')
        macro(f'StSparse{tag}', f'{vpt_min / vpt:g}',
              f'trained minimum {vpt_min:g} vehicles per 10 modules (|V|>={min(TRAIN_FLEET)} at <= {max(TRAIN_SIZES)} modules) over this cell')

        # supplement table row; bold = shortest online arm (GA-60 is a search arm)
        online = {'pdr': best, 'pen': pen, 'ten': ten, 'mix': mix, 'mer': mer}
        win = min(online, key=lambda k: online[k].mean())
        names = {'pdr': f'StPdr{tag}', 'pen': f'StPen{tag}', 'ten': f'StTen{tag}',
                 'mix': f'StMix{tag}', 'mer': f'StMer{tag}'}
        cellf = {k: (f'\\textbf{{\\{v}}}' if k == win else f'\\{v}') for k, v in names.items()}
        srows.append(f'{cellname} & \\StUtil{tag}\\% & {cellf["pdr"]} & \\StGa{tag} & '
                     f'{cellf["pen"]} & {cellf["ten"]} & {cellf["mix"]} & {cellf["mer"]} \\\\')

    macro('StMixCpuShiftMax', f'{max(abs(x) for x in cpu_shift.values()):.2f}',
          'largest |CPU - GPU| change of the deployed policy\'s cell mean, in %, over the two cells')

    # largest merged-head lead over the five production cells (greedy decode):
    # the two cells above plus the three Table III cells of results/scaleup/policy
    leads = {}
    for cell in CELLS.values():
        _, a = policy(MIX, cell)
        _, b = policy(MER, cell)
        leads[cell] = paired_tost(a, b)['mean_rel_diff_pct']
    for cell in ('50x25+ppvct-mixed+v2+t0.6', '50x25+ppvct-mixed+v2+t1.0', '80x25+ppvct-mixed+v3+t1.0'):
        v = []
        for arm in (MIX, MER):
            per_seed = []
            for sd in SEEDS:
                r = json.load(open(f'results/scaleup/policy/{arm}-s{sd}_{cell}.json'))['rows']
                assert all(r[k]['validated'] for k in r)
                per_seed.append([r[k]['ms'] for k in sorted(r)])
            v.append(np.mean(np.array(per_seed, float), axis=0))
        leads[cell] = paired_tost(v[0], v[1])['mean_rel_diff_pct']
    top = max(leads, key=leads.get)
    print('merged-head lead (factorized - merged)/merged, %: '
          + ', '.join(f'{c} {x:+.2f}' for c, x in leads.items()))
    macro('MixSaLeadMax', f'{leads[top]:.1f}',
          f'largest merged-head lead over the five production cells, greedy, in %, at {top}')

    print('\n% ---- macros (scripts/x2_shorttravel_report.py) ----')
    lines = [f'\\newcommand{{\\{name}}}{{{value}}}  % {note}' for name, value, note in out]
    print('\n'.join(lines))
    print('\n% ---- Table III rows (Cell & u & Best PDR & BOLT & CP-SAT 1800 s & CP-SAT 3600 s); '
          'no solver run on these cells; bold = shorter of the two online arms ----')
    print('\n'.join(rows))
    print('\n% ---- supplement table tab:shorttravel rows ----')
    print('\n'.join(srows))

    if WRITE:
        s = open(MACROS).read()
        block = '\n'.join([BEGIN,
                           f'% Sources: {RES}/{{pdr,ga,policy}}/ for {", ".join(CELLS.values())};',
                           '% data/PPVCT/<cell>/test for W_tr. Conventions as scripts/x2_production_macros.py.',
                           *lines, END])
        pat = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END), re.S)
        if pat.search(s):
            s = pat.sub(lambda m: block, s, count=1)
        else:
            for name, _, _ in out:
                assert not re.search(r'\\newcommand\{\\' + name + r'\}', s), f'{name} already defined'
            s = s.rstrip('\n') + '\n\n' + block + '\n'
        open(MACROS, 'w').write(s)
        print(f'\nwrote {len(out)} macros to {MACROS}')
        t = open(SUPP).read()
        pat = re.compile(re.escape(TROWS_BEGIN) + r'.*?' + re.escape(TROWS_END), re.S)
        assert pat.search(t), f'marker comments for tab:shorttravel rows missing in {SUPP}'
        t = pat.sub(lambda m: '\n'.join([TROWS_BEGIN, *srows, TROWS_END]), t, count=1)
        open(SUPP, 'w').write(t)
        print(f'wrote {len(srows)} rows of tab:shorttravel to {SUPP}')


main()
